leftnav:
- identifier: 3223f973-77cb-4674-980a-e9a8c6415e10
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 624b9551-c722-460c-aa34-0360252e964a
  name: 'Investigation 1: Size and Distance'
  pageRef: /pages/investigation-1-size-and-distance
  weight: 20
- identifier: ab202ddb-ee90-4d9c-b053-38d8ff2b5ae8
  name: 'Investigation 2: Light and Color'
  pageRef: /pages/investigation-2-light-and-color
  weight: 30
- identifier: 6567e1bc-f03a-48d3-83a6-d3a8d10a9fe1
  name: 'Investigation 3: Production of Light'
  pageRef: /pages/investigation-3-production-of-light
  weight: 40
- identifier: f1d842a8-a6ce-4607-907b-cdc43e61de22
  name: 'Investigation 4: Supernova Remnants'
  pageRef: /pages/investigation-4-supernova-remnants
  weight: 50
- identifier: 557068e9-aef8-4fea-96d3-2835e1046de1
  name: 'Investigation 5: Variable X-ray Sources'
  pageRef: /pages/investigation-5-variable-x-ray-sources
  weight: 60
- identifier: 4da71100-b02d-444e-b1a2-cba178524ceb
  name: 'Investigation 6: Galaxy Clusters'
  pageRef: /pages/investigation-6-galaxy-clusters
  weight: 70
- identifier: cc8daef2-68d9-4c36-b5bb-c933c57f103f
  name: 'Activity 1 '
  pageRef: /pages/investigation-1-size-and-distance-activity-1
  parent: 624b9551-c722-460c-aa34-0360252e964a
  weight: 10
- identifier: ecba92d9-b465-4db2-8e62-f3ae11248eeb
  name: Activity 2
  pageRef: /pages/investigation-1-size-and-distance-activity-2
  parent: 624b9551-c722-460c-aa34-0360252e964a
  weight: 20
- identifier: 3099d511-c56a-4816-833f-b79da2991f1d
  name: Activity 3
  pageRef: /pages/investigation-1-size-and-distance-activity-3
  parent: 624b9551-c722-460c-aa34-0360252e964a
  weight: 30
- identifier: 84027003-c25e-4d85-a77c-758fdccabc4a
  name: Activity 4
  pageRef: /pages/investigation-1-size-and-distance-activity-4
  parent: 624b9551-c722-460c-aa34-0360252e964a
  weight: 40
- identifier: 8c28079a-82b5-4be9-ad0d-f94962568638
  name: Activity 5
  pageRef: /pages/investigation-1-size-and-distance-activity-5
  parent: 624b9551-c722-460c-aa34-0360252e964a
  weight: 50
- identifier: 2a84c2e4-aca0-478b-aa39-f6a7197770e2
  name: Activity 6
  pageRef: /pages/investigation-1-size-and-distance-activity-6
  parent: 624b9551-c722-460c-aa34-0360252e964a
  weight: 60
- identifier: 6a290ccd-992b-432e-acee-d00c15759f05
  name: 'Activity 1 '
  pageRef: /pages/investigation-2-light-and-color-activity-1
  parent: ab202ddb-ee90-4d9c-b053-38d8ff2b5ae8
  weight: 10
- identifier: bb1d0c90-031d-4fd8-b970-edaabac98829
  name: Activity 2
  pageRef: /pages/investigation-2-size-and-distance-activity-2
  parent: ab202ddb-ee90-4d9c-b053-38d8ff2b5ae8
  weight: 20
- identifier: e3104162-f200-4b58-8321-c931c651eeb1
  name: Activity 3
  pageRef: /pages/investigation-2-size-and-distance-activity-3
  parent: ab202ddb-ee90-4d9c-b053-38d8ff2b5ae8
  weight: 30
- identifier: 7b8b6ef7-48c3-4512-824a-79084e0691f7
  name: Activity 4
  pageRef: /pages/investigation-2-size-and-distance-activity-4
  parent: ab202ddb-ee90-4d9c-b053-38d8ff2b5ae8
  weight: 40
- identifier: f924523a-bc75-4c6b-918b-99aa9c514a7e
  name: Activity 5
  pageRef: /pages/investigation-2-size-and-distance-activity-5
  parent: ab202ddb-ee90-4d9c-b053-38d8ff2b5ae8
  weight: 50
- identifier: a4a99b13-49f6-43d2-9f29-fc2cd0123cba
  name: Activity 6
  pageRef: /pages/investigation-2-size-and-distance-activity-6
  parent: ab202ddb-ee90-4d9c-b053-38d8ff2b5ae8
  weight: 60
- identifier: bfb29872-76eb-4468-bee6-6776fb8535db
  name: Activity 7
  pageRef: /pages/investigation-2-light-and-color-activity-7
  parent: ab202ddb-ee90-4d9c-b053-38d8ff2b5ae8
  weight: 70
- identifier: 0722da69-f006-4c37-badb-f8c02e327d6d
  name: 'Activity 1 '
  pageRef: /pages/investigation-3-production-of-light-activity-1
  parent: 6567e1bc-f03a-48d3-83a6-d3a8d10a9fe1
  weight: 10
- identifier: 470c67a1-740d-4aba-9659-0e037cf9b1d6
  name: Activity 2
  pageRef: /pages/investigation-3-production-of-light-activity-2
  parent: 6567e1bc-f03a-48d3-83a6-d3a8d10a9fe1
  weight: 20
- identifier: c8a0fddc-c8fc-4dd5-8694-605dd4e9c0d4
  name: Activity 3
  pageRef: /pages/investigation-3-production-of-light-activity-3
  parent: 6567e1bc-f03a-48d3-83a6-d3a8d10a9fe1
  weight: 30
- identifier: a3d9f6b0-af3c-4b1f-afec-81d8971efc43
  name: Activity 4
  pageRef: /pages/investigation-3-production-of-light-activity-4
  parent: 6567e1bc-f03a-48d3-83a6-d3a8d10a9fe1
  weight: 40
- identifier: 7cbfaacd-f9d9-46d0-954a-19b64baa017e
  name: Activity 5
  pageRef: /pages/investigation-3-production-of-light-activity-5
  parent: 6567e1bc-f03a-48d3-83a6-d3a8d10a9fe1
  weight: 50
- identifier: 592365ed-8425-42cc-8a96-4a9af5fe9880
  name: Activity 6
  pageRef: /pages/investigation-3-production-of-light-activity-6
  parent: 6567e1bc-f03a-48d3-83a6-d3a8d10a9fe1
  weight: 60
- identifier: db2d5b40-b2bd-4733-b5ca-7f057dba3aa3
  name: 'Activity 1 '
  pageRef: /pages/investigation-4-supernova-remnants-activity-1
  parent: f1d842a8-a6ce-4607-907b-cdc43e61de22
  weight: 10
- identifier: 95e6b0f7-d095-4c6f-bd3e-03916e304bfb
  name: Activity 2
  pageRef: /pages/investigation-4-supernova-remnants-activity-2
  parent: f1d842a8-a6ce-4607-907b-cdc43e61de22
  weight: 20
- identifier: fdadf712-71a0-44d8-9781-6f0656b9fdcc
  name: Activity 3
  pageRef: /pages/investigation-4-supernova-remnants-activity-3
  parent: f1d842a8-a6ce-4607-907b-cdc43e61de22
  weight: 30
- identifier: 987231cc-33f3-4b67-80ec-a62d43ca53ad
  name: Activity 4
  pageRef: /pages/investigation-4-supernova-remnants-activity-4
  parent: f1d842a8-a6ce-4607-907b-cdc43e61de22
  weight: 40
- identifier: 44bffa8a-b6c1-4a13-86c1-453a5e09728a
  name: Activity 5
  pageRef: /pages/investigation-4-supernova-remnants-activity-5
  parent: f1d842a8-a6ce-4607-907b-cdc43e61de22
  weight: 50
- identifier: e2d39f0a-6008-4a0d-a1f5-f099eab89871
  name: Activity 6
  pageRef: /pages/investigation-4-supernova-remnants-activity-6
  parent: f1d842a8-a6ce-4607-907b-cdc43e61de22
  weight: 60
- identifier: ccc32659-fbc9-4266-b85b-683b348707b6
  name: 'Activity 1 '
  pageRef: /pages/investigation-5-variable-x-ray-sources-activity-1
  parent: 557068e9-aef8-4fea-96d3-2835e1046de1
  weight: 10
- identifier: ea8eced3-10f2-44c2-ae16-32c206ff5f68
  name: Activity 2
  pageRef: /pages/investigation-5-variable-x-ray-sources-activity-2
  parent: 557068e9-aef8-4fea-96d3-2835e1046de1
  weight: 20
- identifier: 9daf902d-d9a7-4ef4-931a-493ca243feff
  name: Activity 3
  pageRef: /pages/investigation-5-variable-x-ray-sources-activity-3
  parent: 557068e9-aef8-4fea-96d3-2835e1046de1
  weight: 30
- identifier: 2a5ae59d-331a-47f9-9c32-a30aa3a8a48d
  name: Activity 4
  pageRef: /pages/investigation-5-variable-x-ray-sources-activity-4
  parent: 557068e9-aef8-4fea-96d3-2835e1046de1
  weight: 40
- identifier: 678e0f28-d501-4c80-a915-74d10a7d7641
  name: Activity 5 & 6
  pageRef: /pages/investigation-5-variable-x-ray-sources-activity-5-6
  parent: 557068e9-aef8-4fea-96d3-2835e1046de1
  weight: 50
- identifier: 50c1682a-8a82-4e13-ba44-0a1a415fd30e
  name: Activity 1
  pageRef: /pages/investigation-6-galaxy-clusters-activity-1
  parent: 4da71100-b02d-444e-b1a2-cba178524ceb
  weight: 10
- identifier: 9c5d85af-fbcc-46a5-8685-bca2de9e6e88
  name: Activity 2
  pageRef: /pages/investigation-6-galaxy-clusters-activity-2
  parent: 4da71100-b02d-444e-b1a2-cba178524ceb
  weight: 20
- identifier: 92b42663-d1bf-4e7c-9acd-8b22577ddc4b
  name: Activity 3
  pageRef: /pages/investigation-6-galaxy-clusters-activity-3
  parent: 4da71100-b02d-444e-b1a2-cba178524ceb
  weight: 30
- identifier: 39b20dfd-1430-4d4c-a4a3-9d2568883c85
  name: Activity 4
  pageRef: /pages/investigation-6-galaxy-clusters-activity-4
  parent: 4da71100-b02d-444e-b1a2-cba178524ceb
  weight: 40
- identifier: 526faffe-a07b-40c8-bf81-7928ef709b52
  name: Activity 5
  pageRef: /pages/investigation-6-galaxy-clusters-activity-5
  parent: 4da71100-b02d-444e-b1a2-cba178524ceb
  weight: 50
